### ISSUE TITLE
Package name should respect naming convention

### ISSUE THREAD

**Issue by pigne** [graphstream/gs-ui-javafx#1]
According to the java  [packages naming convention](https://docs.oracle.com/javase/tutorial/java/package/namingpkgs.html) packages should not contain upper case letters :  e.g. `org.graphstream.ui.viewer_fx` instead of `org.graphstream.ui.viewerFx`.

**Comment by hichbra** [comment]
Done in gs-ui-(swing/javafx). We should change the graphicGraph package in gs-core too.
