### ISSUE TITLE
Current design does not allow several viewers

### ISSUE THREAD

**Issue by gsavin** [graphstream/gs-ui-javafx#10]
# Steps to reproduce

There are two scenarios (so far) which can lead to this problem:
1. Calling `display()` several time, on the same graph or on different graphs
2. Calling `display()` from a JavaFX application

Example:
```java
public static void main(String[] args) {
    System.setProperty("org.graphstream.ui", "javafx");

    Graph g1 = new AdjacencyListGraph("g1");
    Graph g2 = new AdjacencyListGraph("g2");
    g1.display();
    g2.display();
}
```

# Expected

I should be able to display two graphs at the same time, or to get the viewer through `display()` from another JavaFX application.

# What we got

Since the `Display` of `gs-ui-javafx` is using an `Application`, and that JavaFX seems not to be happy with several applications, the following exception occurred:

```
Exception in thread "Thread-7" java.lang.IllegalStateException: Application launch must not be called more than once
	at com.sun.javafx.application.LauncherImpl.launchApplication(LauncherImpl.java:162)
	at com.sun.javafx.application.LauncherImpl.launchApplication(LauncherImpl.java:143)
	at javafx.application.Application.launch(Application.java:191)
	at org.graphstream.ui.javafx.util.Display.lambda$display$0(Display.java:33)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by hichbra** [comment]
Display should not be called from a JavaFX Application. If you build an Application, I think the view must be added manually.

**Comment by gsavin** [comment]
Not sure to understand why display *should not be called* from another application? Except for technical reasons linked to the current implementation. We should keep in mind that GraphStream aims to be a library and not a final software, therefore it should be as flexible as possible for users.

But in the example I gave, display is not called from another application. It's just two sequential calls to any display method, called from the main method. It's easy to imagine a scenario where one wants to display two graphs at the same time (a graph and an higher level view of this graph for example).

**Comment by hichbra** [comment]
I'm sorry I was not clear.
To the first point I fully agree, display() can be used several times, it was a bug and I already sent a commit to resolve that.
I was talking about the second point. It's just my opinion, but currently gs-ui-javafx use a class called DefaultApplication for display a graph. As its name suggests, this class was created in case of a user want quickly see and use a graph without build an entire interface. 
When he implement Application (and so build his interface), he should not use display(), but add the view in his own Scene, Panel or what he want.
But of course I understand this should not stay like this, with the Exception. I already started looking for a solution.
