### ISSUE TITLE
Jar File and Maven

### ISSUE THREAD

**Issue by CHIODELLIz** [graphstream/gs-ui-javafx#11]
Hello, I'd like to know where the jar is and dependence on maven.
Thank you :)

**Comment by hichbra** [comment]
Hi ! This project is part of Graphstream 2.0 and is not yet released.
For the previous versions, see here :
http://graphstream-project.org/download/
http://graphstream-project.org/doc/Tutorials/GraphStream-Maven/

**Comment by vishrantgupta** [comment]
@hichbra is it possible to release snapshot version of Graphstream 2.0 with JavaFX support?
Thanks.

**Comment by pigne** [comment]
Preview 2.0 releases are now available : 

https://github.com/graphstream/gs-core/releases/tag/2.0-alpha
https://github.com/graphstream/gs-ui-javafx/releases/tag/2.0-alpha
