### ISSUE TITLE
Coordinate system does not work 

### ISSUE THREAD

**Issue by dig22** [graphstream/gs-ui-javafx#13]
`viewer.disableAutoLayout();`
`node.setAttribute("xyz" ,event.getX()   , event.getY() , 0 );`

**the above has no effect, please advice**

**Comment by hichbra** [comment]
Disable your autoFit parameter 
```java 
panel.getCamera().setAutoFitView(false);
```
And try to convert your values before
```java 
Node n = graph.addNode("N1");
Point3 p = panel.getCamera().transformPxToGu(e.getX(), e.getY()) ;
n.setAttribute("xyz",new double[] { p.x, p.y, 0 });	 
```
