### ISSUE TITLE
Ui has rotated 180 degree

### ISSUE THREAD

**Issue by ajoydas** [graphstream/gs-ui-javafx#14]
I am running this [test](https://github.com/graphstream/gs-ui-javafx/blob/master/src-test/org/graphstream/ui/viewer/test/DemoViewerFxEdgeSelection.java) from the repo. But the ui is rotated 180 degree. So if I drag the mouse downwards it shows in the upward direction on the view.

![image](https://user-images.githubusercontent.com/13214835/48933470-927b0200-ef2a-11e8-960a-22ff453f56c7.png)

**Comment by hichbra** [comment]
That's strange, it's working well for me. This problem is just for this test ?
Which branch/version of gs-core are you using ?
