### ISSUE TITLE
2nd size value is ignored (nodes always squares)

### ISSUE THREAD

**Issue by damian-anlauf** [graphstream/gs-ui-javafx#16]
When defining two or more size values in the stylesheet only the first value is used and thus nodes can't be rectangular. 

The issue lies in line 105 in /src/org/graphstream/ui/javafx/renderer/shape/javafx/Area.java.

The value of `camera.getMetrics().lengthToGu(style.getSize(), 1) ;` is discarded in that line while it should be saved in `double h`.

**Comment by hichbra** [comment]
Indeed ! I will fix that immediately.
