### ISSUE TITLE
How to build

### ISSUE THREAD

**Issue by jordilaforge** [graphstream/gs-ui-javafx#2]
Hey how can I get this to compile?

I tried it with the most recent branch 2.x for gs-core no luck and I tried the master for gs-core.
For example:
import org.graphstream.ui.view.util.GraphMetrics;
Is in your code but it is not present on the branch 2.x at the same place.
Can you give some information on how to build this project?
Thank you

**Comment by hichbra** [comment]
Hi ! 

Actually this version is still in development, we have not yet merged in gs-core. If you want to compile this, you must use my own version with the branch uiScalaToJava : https://github.com/hichbra/gs-core/tree/uiScalaToJava .

**Comment by jordilaforge** [comment]
ok perfect thank you
