### ISSUE TITLE
Can't interact with graph when incorporated in another JavaFX component

### ISSUE THREAD

**Issue by VersusF** [graphstream/gs-ui-javafx#21]
Hello.
I'm using this version of graphstream to incorporate a graph into a border pane with other informations. The problem is that when i show the stage i can't move the nodes with the mouse. Instead if I show the graph with `graph.display()` I can move them.

Here is my code:
```java
FXMLLoader loader = new FXMLLoader(getClass().getResource(CFG_VIEWER_PATH));
BorderPane root = loader.load();
mCfgViewerController = loader.getController();
FxViewPanel cfgView = cfg.getView();
root.setCenter(cfgView);
Stage stage = new Stage();
stage.setTitle(file.getName());
stage.setScene(new Scene(root));
stage.initModality(Modality.APPLICATION_MODAL);
stage.show();
```

where the function `getView` builds it like this
```java
// Graph creation skipped
mView = new FxViewer(mGraph, FxViewer.ThreadingModel.GRAPH_IN_ANOTHER_THREAD);
mView.enableAutoLayout();
return (FxViewPanel) mView.addView(FxViewer.DEFAULT_VIEW_ID, new FxGraphRenderer());
```

Thanks for the help

_Originally posted by @VersusF in https://github.com/graphstream/gs-ui-javafx/issues/12#issuecomment-505932551_

**Comment by hichbra** [comment]
Hi,

It's because the elements are added in the same panel as the graph, due to that, the view panel cannot get the right coordinates.
You can easily prevent that by providing the graph its own panel. 

Try to change your ```getView``` function by : 
```java
FxViewer mView = new FxViewer(graph, FxViewer.ThreadingModel.GRAPH_IN_ANOTHER_THREAD);
mView.enableAutoLayout();
FxViewPanel panel = (FxViewPanel) mView.addView(FxViewer.DEFAULT_VIEW_ID, new FxGraphRenderer());
		
StackPane graphPane = new StackPane();
graphPane.getChildren().addAll(panel); // prevent UI shift issues
		
return graphPane;
```

**Comment by VersusF** [comment]
That worked perfectly, and the listeners too.
Thank you so much
