### ISSUE TITLE
Threads and mouse events

### ISSUE THREAD

**Issue by BaptisteDebes** [graphstream/gs-ui-javafx#22]
Hi, I'm trying to implement the simple click and print feature you introduce in the tutorial but I'm confused about threading and I think I messed it up a little bit. I'm working with JavaFX.

Here is the viewer code.

		
	        this.graph = new MultiGraph("color_link");
		this.viewer = new FxViewer(this.graph, FxViewer.ThreadingModel.GRAPH_IN_GUI_THREAD);
		this.graph.setAttribute("ui.antialias");
		this.graph.setAttribute("ui.quality");
		String styleSheet = "graph {padding: 60px;}";

		this.graph.setAttribute("ui.stylesheet", styleSheet);
		this.viewer.enableAutoLayout();
		FxViewPanel panel = (FxViewPanel)this.viewer.addDefaultView(false, new FxGraphRenderer());
		panel.resize(300, 300);
		this.hbox.getChildren().addAll(panel);
		
		this.setSliderActions();
		
		ViewerPipe viewer_pipe = this.viewer.newViewerPipe();
		viewer_pipe.addViewerListener(new Click());
		viewer_pipe.addSink(this.graph);

Here is the Click class, I changed the example code, because as I said I'm confused with the threading and I thought it would work like this.

``class Click implements ViewerListener {

	public void viewClosed(String id) {
		
	}

	public void buttonPushed(String id) {
		System.out.println("Button pushed on node "+id);
	}

	public void buttonReleased(String id) {
		System.out.println("Button released on node "+id);
	}

	@Override
	public void mouseLeft(String arg0) {
		
	}

	@Override
	public void mouseOver(String arg0) {
		
	}
}``

There are many different ways to style code with GitHub's markdown. If you have inline code blocks, wrap them in backticks: .  If you've got a longer block of code, you can indent with four spaces:

**Comment by hichbra** [comment]
Hi, 

First, you can change ```ThreadingModel.GRAPH_IN_GUI_THREAD``` by  ```ThreadingModel.GRAPH_IN_ANOTHER_THREAD```.

Also, as explained [here](http://graphstream-project.org/doc/Tutorials/Graph-Visualisation/), you need to call pump() to handle events if you wanted to create your own UI. 
```java
new Thread( () -> {
	while( loop ) {
		viewer_pipe.pump();
		Thread.sleep(100); 
	}
}).start();
```
This should come before any event, and so before adding nodes/edges.
