### ISSUE TITLE
FxDefaultView is not abstract and does not override abstract method enableMouseOptions()

### ISSUE THREAD

**Issue by jboydon** [graphstream/gs-ui-javafx#23]
I compiled this library using jdk 1.8 and gs libraries version 2.0.0-beta and I have got this error:

`[ERROR] /Users/puggelli/Development/Tests/GraphStream/gs-ui-javafx/src/org/graphstream/ui/fx_viewer/FxDefaultView.java:[106,8] org.graphstream.ui.fx_viewer.FxDefaultView is not abstract and does not override abstract method enableMouseOptions() in org.graphstream.ui.view.View
`

regards
  john

**Comment by hichbra** [comment]
You must use the same version for every packages. The beta version is not yet released for javafx, you need to stay in the alpha version.
