### ISSUE TITLE
Mouse events not handled with BorderPane

### ISSUE THREAD

**Issue by jboydon** [graphstream/gs-ui-javafx#24]
Hello,
there is a problem with FxViewPanel. When I add it inside a BorderPane, if there is another Pane on top or left, then the mouse events are not handled anymore.

Please have a look to this example (modified version of DemoAllInFx):

`

	@Override public void start(Stage primaryStage) throws Exception {
		Graph graph  = new MultiGraph("mg");
		
		FxViewer viewer = new FxViewer(graph, FxViewer.ThreadingModel.GRAPH_IN_GUI_THREAD);

		graph.addNode("A");
		graph.addNode("B");
		graph.addNode("C");
		graph.addEdge("AB", "A", "B");
		graph.addEdge("BC", "B", "C");
		graph.addEdge("CA", "C", "A");
		graph.setAttribute( "ui.antialias" );
		graph.setAttribute( "ui.quality" );
		graph.setAttribute( "ui.stylesheet", styleSheet );
   
		graph.getNode("A").setAttribute("xyz", -1, 0, 0 );
		graph.getNode("B").setAttribute("xyz",  1, 0, 0 );
  		graph.getNode("C").setAttribute("xyz",  0, 1, 0 );
     		
  		FxViewPanel v =  (FxViewPanel) viewer.addDefaultView( false ) ;

		BorderPane pane = new BorderPane();
		//pane.setTop(new Label("Top"));	// With top or left the mouse events are not
		pane.setLeft(new Label("Left"));	// handled anymore. While right and bottom are ok. 
		pane.setRight(new Label("Right"));
		pane.setBottom(new Label("Bottom"));
		pane.setCenter(v);

  		Scene scene = new Scene(pane, 800, 600);
  		primaryStage.setScene(scene);
  				
		primaryStage.show();
	}
`

regards
  John

**Comment by hichbra** [comment]
Hi!

This issue is related to https://github.com/graphstream/gs-ui-javafx/issues/21 I think. Can you try it ?

**Comment by jboydon** [comment]
Solution used in #21 works perfectly.
`
        final StackPane result = new StackPane();
        result.getChildren().addAll(view); // prevent UI shift issues
`

Thanks
  John
