### ISSUE TITLE
Two graphs in one frame

### ISSUE THREAD

**Issue by aaron-sr** [graphstream/gs-ui-javafx#25]
Hi,

I tested one of the provided test classes: [src-test/org/graphstream/ui/viewer_fx/test/TestTwoViewersInOneFrame.java
](https://github.com/graphstream/gs-ui-javafx/blob/2.0-alpha/src-test/org/graphstream/ui/viewer_fx/test/TestTwoViewersInOneFrame.java)
While the graphs are shown properly, I'm only able to move nodes of the first graph. 
The nodes of the other graph are not clickable, only the selection rectangle occurs.

![gui](https://user-images.githubusercontent.com/29255771/86922812-7642cd80-c12d-11ea-843f-528cd5b1f386.png)

EDIT: I tested two separate Stages/Scenes, both handle click-move events as intented.

Greetings

**Comment by hichbra** [comment]
Hi, 

Yes this issue is related to https://github.com/graphstream/gs-ui-javafx/issues/21 and going to be fixed in the next release. Thank you.
