### ISSUE TITLE
Remove Basic Renderer

### ISSUE THREAD

**Issue by pigne** [graphstream/gs-ui-javafx#5]
Since the full version is functional, should the `BasicRenderer` be removed?

**Comment by hichbra** [comment]
Removal of FxBasicGraphRenderer https://github.com/graphstream/gs-ui-javafx/commit/e5a043a039a4dbf85f31df4a57be15642dc97788 and FxFullGraphRenderer renaming https://github.com/graphstream/gs-ui-javafx/commit/e2d2616a8b4c610e9fea0e2dc736c232427ce09a.
